name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node
        run: |
          npm install -g react-native-cli
          npm install -g detox-cli
      - name: Install Detox
        run: |
          brew tap wix/brew
          brew install applesimutils
      - name: Install Node Dependencies
        run: npm install
      - name: Unit Tests
        run: npm test
      - name: Detox Build Android
        run: detox build --configuration android.emu.release
      - name: Detox Test
        run: detox test --configuration android.emu.release --cleanup
