name: Test

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v1

      - name: Specify node version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Use specific Java version for sdkmanager to work
        uses: joschi/setup-jdk@v1
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          java-version: 'openjdk8'
          architecture: 'x64'

      - name: Download Android Emulator Image
        run: |
          echo y | sudo $ANDROID_HOME/tools/bin/sdkmanager --verbose "system-images;android-27;google_apis;x86"
          $ANDROID_HOME/tools/bin/avdmanager create avd -n emu -k "system-images;android-27;google_apis;x86" -b "x86" -c 1G -d 7 -f
      - name: Install node_modules
        run: |
          npm install
          detox build --configuration android.emu.release
      - name: Android test
        timeout-minutes: 10
        run: |
          mkdir -p artifacts
          export PATH=$PATH:$ANDROID_HOME/platform-tools
          $ANDROID_HOME/emulator/emulator @emu &
          adb wait-for-device; adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'; adb shell wm dismiss-keyguard
          detox test --configuration android.emu.release --cleanup
